# Site settings
title: Writing and Stuff
email: matalina@gmail.com
description: ""
baseurl: ""
url: "http://matalina.github.io"
twitter_username: matalina
github_username:  matlaina

# Build settings
markdown: kramdown
permalink: pretty

timezone: America/Chicago

kramdown:
  input: GFM
